export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_LABELS = 'FETCH_LABELS';
export const SELECT_LABEL = 'SELECT_LABEL';
export const DESELECT_LABEL = 'DESELECT_LABEL';

export default {
  FETCH_ARTICLES,
  FETCH_LABELS,
  SELECT_LABEL,
  DESELECT_LABEL
};
